apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.1.2@sha256:d17d10f8d1ad50f887ad6d9964b9aa307f7e449ca3cb2781ef157a40556f8b5a
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 6767
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open-page-variant"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "bazarr.${SECRET_DOMAIN}"
            secretName: "bazarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
      media:
        enabled: true
        type: nfs
        server: "192.168.1.4"
        path: /mnt/pool-01/media/
        mountPath: /media/
        readOnly: false
