---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app whoogle
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: *app
    image:
      repository: docker.io/benbusby/whoogle-search
      tag: 0.7.2
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "whoogle.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "whoogle-tls"
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 250Mi
