---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghost
      tag: 5.25.0
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
      url: "https://blog.${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ghost-mysql
      database__connection__user: ghost
      database__connection__password: ${SECRET_GHOST_MYSQL_PASSWORD}
      database__connection__database: ghost
      NODE_ENV: production
    service:
      main:
        ports:
          http:
            port: 2368
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "ghost"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"

        hosts:
          - host: "blog.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "blog.${SECRET_DOMAIN}"
            secretName: "blog-tls"
    persistence:
      content:
        enabled: true
        existingClaim: ghost-config
        mountPath: /var/lib/ghost/content
