---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ghost
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      reposistory: ghost
      tag: "5.0.0"
    env:
      TZ: "${TIMEZONE}"
      url: "https://blog.${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ghost-mysql
      database__connection__user: ghost
      database__connection__password: ${SECRET_GHOST_MYSQL_PASSWORD}
      database__connection__database: ghost
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "ghost"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: "blog.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "blog.${SECRET_DOMAIN}"
            secretName: "blog-tls"
    persistence:
      content:
        enabled: true
        existingClaim: ghost-config
    mariadb:
      enable: false
