# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:SE5w0u5nMBAeUga3cnxr4zw//nw=,iv:aBoQhbZ5OKi+8lpdjIP9wC6WFCZmyQ9XY0d0jig5GPg=,tag:olN48DKxtX9ctJcIb3XWtQ==,type:str]
    api-key: ENC[AES256_GCM,data:Fp5PfvV/GEgU6/GrcRZmyJtX0sbSgie5l19ZwB27gWMFx6B/4A==,iv:LDYnzeUNLUi+L6cFZ0jJOepwmBYyB4OchZbF6fOt0zk=,tag:ajNlx+1gsbF8y9wL8C9n+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fn8m6nvmzt4w65fg8ylkt2md2q5rrk3a2aqp4zw0kmw9g0d3zeksk2r7cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZTRGKy9XeUNYMmxKUTRI
            R3Fnd3ArcjZQT2ZRc3B5ZG5VSGlyNURBbUJnCkNCVm1wU1htZk5YSjBrUDJLU3Fa
            R0l5K3NSdEFPQ3hndW5MY1dRVW5LZGcKLS0tIHU3cy9RQ1VoSURMZG8wYmRDRXBh
            R3JsWks5eTBkR04yQVhoNklNNTl3SG8KDyLOMhEJl2c8MimanpNERQhaCcLtY7I8
            7EDUIEq7ToIQHb6ZVDkwUIsr2TKp/iKYPU1HWjIOxe1XQwB6CjPyeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T20:01:04Z"
    mac: ENC[AES256_GCM,data:gICmjUbVdZZmLcxlMH8/GnK5ojj4yeAJSx9UOlbBbhVn2TlKmTIR0WFk2oclNL+Ju2JdekNXOoHEMdLfq0sWVq65CAlN4WUkGdUREgY1tQMWuLXlOJ7HA+KKJN0kG7SBm0/RPY9CgfLDeF0TXeaRZQ9d+OWpvQ/f0t5HJArMMoU=,iv:RUKqt/0BkXiQktmoCI1wTkSDUTYtm6omDNW0B1kWU3w=,tag:kGsytSQOzogkihiVGh0jPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
