# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:j2e+n/zJA8VNJZftVSLtOoQygqA=,iv:ryTKzl1vto4OWDv51+6v+F4HAY4wXo1cmhhbP9RhoJ0=,tag:vmYFlZQfNKywWSkd7supwA==,type:str]
    api-key: ENC[AES256_GCM,data:OycbTv2Xtj+02DOb+f3/AeG+4cSlRtYk/DOOt19WQQCCA+bIRw==,iv:qB5Jqe8u29ng/SeARumw9q2OC3hFdWSPynyulKTD8Z4=,tag:IyQLHOgB0Bn3lli6B5wukg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fn8m6nvmzt4w65fg8ylkt2md2q5rrk3a2aqp4zw0kmw9g0d3zeksk2r7cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb3g4K29lVDFpUW5qTWxI
            b0lXQlhIR0x3OVc3ZzNTRmFXYmtpY1plYVdJCmNZRk5BWWNGQmFXTWF0czRtYzlw
            L0tpcGoxNnhHcGh4OUtNTjZrNmUrcjgKLS0tIDBtb1QrUlJ0TmJpdlprSVZZUi9l
            dGozZW12OHdnT0RDQ2o1cUNtd0RNaWsKZoQwzlVwKlxOxPlZrP0eVVxth+AUuIb6
            2HL4rFgK3zhjp6zZ1ErzPJKq1N0GJsYq5gwGgesfAW+VGJkx2tCnsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-20T12:20:41Z"
    mac: ENC[AES256_GCM,data:ctLVyS1K7zFeIiqgMAUoY75OuPoEzdMsATrpO2lbLqiqHUHKkO3Xt90bF+G8bbOy0u/Y4uZeery66s6WwshWAwDcF7x6WmDGjGK80Uk6Udrulfcqa60Dax/T6hxGDJgfpeIz9P/oqRI7wGN7po7/PZNxosSflnGHSQ+Dw8FFDnI=,iv:JNa6dZxbjsiu3M4173Cnvv7FLiWKWBQ7KSEv/jbScF8=,tag:gZK/msz6zq2OfwEBfxVnew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
