---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-v3
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
