---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-v11
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
