apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/readarr-nightly
      tag: 0.1.1.1459@sha256:845c1aedff10ec9db965c9dc5080aa4dda9e4e3173c49a56f6bd70b62a3b346e
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
      PUID: "${SECURITY_CONTEXT_RUN_AS_USER}"
      PGID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    service:
      main:
        ports:
          http:
            port: 8787
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open-page-variant"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "readarr.${SECRET_DOMAIN}"
            secretName: "readarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config-v5
      media:
        enabled: true
        type: nfs
        server: "192.168.1.4"
        path: /mnt/pool-01/media/
        mountPath: /media/
        readOnly: false
      downloads:
        enabled: true
        type: nfs
        server: "192.168.1.4"
        path: /mnt/Cache/downloads
        mountPath: /downloads
        readOnly: false
